simple_gimbal_controller:
  yaw_joint_name:
    type: string
    description: "Yaw joint controlled by the gimbal controller."
    validation:
      not_empty<>: []
  pitch_joint_name:
    type: string
    description: "Pitch joint controlled by the gimbal controller."
    validation:
      not_empty<>: []
  command_interface_name:
    type: string
    description: "Command interface used for yaw and pitch joints."
    validation:
      not_empty<>: []
  state_interface_name:
    type: string
    description: "State interface used for yaw and pitch joints."
    validation:
      not_empty<>: []
  pitch_lower_limit:
    type: double
    description: "Lower pitch command limit."
  pitch_upper_limit:
    type: double
    description: "Upper pitch command limit."
