teleop_remote_controller:
  cmd_vel_topic:
    type: string
    description: "Teleop velocity command topic."
    validation:
      not_empty<>: []
  cmd_gimbal_topic:
    type: string
    description: "Teleop gimbal angular velocity command topic."
    validation:
      not_empty<>: []
  mode_topic:
    type: string
    description: "Teleop chassis mode command topic."
    validation:
      not_empty<>: []
  shooter_mode_topic:
    type: string
    description: "Teleop shooter mode command topic."
    validation:
      not_empty<>: []
  command_timeout:
    type: double
    description: "Maximum age of cmd_vel before zeroing velocity. Non-positive disables timeout."
