#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
generated_dir="$SCRIPT_DIR/../.generated"
output_file="$generated_dir/docker-compose.local.override.yml"
repo_root="$(cd "$SCRIPT_DIR/../.." && pwd)"
host_uname="$(uname -s)"

environment_entries=""
mounts=""
extra_service_entries=""

escape_yaml_double_quoted() {
    value=$1
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}
    printf '%s' "$value"
}

normalize_host_path() {
    local path_value="$1"

    if command -v cygpath >/dev/null 2>&1; then
        cygpath -m "$path_value"
    else
        printf '%s' "$path_value"
    fi
}

add_env() {
    env_name=$1
    env_value=$2
    escaped_env_value=$(escape_yaml_double_quoted "$env_value")

    if [ -n "$environment_entries" ]; then
        environment_entries="${environment_entries}      ${env_name}: \"${escaped_env_value}\"\n"
    else
        environment_entries="      ${env_name}: \"${escaped_env_value}\"\n"
    fi
}

add_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        normalized_host_path=$(normalize_host_path "$host_path")
        escaped_host_path=$(escape_yaml_double_quoted "$normalized_host_path")
        escaped_target_path=$(escape_yaml_double_quoted "$target_path")
        mounts="${mounts}      - type: bind\n        source: \"${escaped_host_path}\"\n        target: \"${escaped_target_path}\"\n"
    fi
}

add_ro_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        normalized_host_path=$(normalize_host_path "$host_path")
        escaped_host_path=$(escape_yaml_double_quoted "$normalized_host_path")
        escaped_target_path=$(escape_yaml_double_quoted "$target_path")
        mounts="${mounts}      - type: bind\n        source: \"${escaped_host_path}\"\n        target: \"${escaped_target_path}\"\n        read_only: true\n"
    fi
}

add_service_entry() {
    entry_text=$1

    if [ -n "$extra_service_entries" ]; then
        extra_service_entries="${extra_service_entries}${entry_text}\n"
    else
        extra_service_entries="${entry_text}\n"
    fi
}

add_env "HOST_WORKSPACE_FOLDER" "$(normalize_host_path "$repo_root")"

if [ -n "${DISPLAY:-}" ]; then
    add_env "DISPLAY" "$DISPLAY"
fi
if [ -n "${HTTP_PROXY:-}" ]; then
    add_env "HTTP_PROXY" "$HTTP_PROXY"
fi
if [ -n "${HTTPS_PROXY:-}" ]; then
    add_env "HTTPS_PROXY" "$HTTPS_PROXY"
fi
if [ -n "${NO_PROXY:-}" ]; then
    add_env "NO_PROXY" "$NO_PROXY"
fi
if [ -n "${http_proxy:-}" ]; then
    add_env "http_proxy" "$http_proxy"
fi
if [ -n "${https_proxy:-}" ]; then
    add_env "https_proxy" "$https_proxy"
fi
if [ -n "${no_proxy:-}" ]; then
    add_env "no_proxy" "$no_proxy"
fi

add_mount "$HOME/.codex" "/root/.codex"
add_mount "$HOME/.claude" "/root/.claude"
add_mount "$HOME/.claude.json" "/root/.claude.json"
add_mount "$HOME/.lark-cli" "/root/.lark-cli"
add_mount "$HOME/.config/opencode" "/root/.config/opencode"
add_mount "$HOME/.local/share/lark-cli" "/root/.local/share/lark-cli"
add_mount "$HOME/.local/share/opencode" "/root/.local/share/opencode"
add_ro_mount "$HOME/.agents/skills" "/root/.agents/skills"

case "$host_uname" in
    Linux*)
        if [ -e "/dev" ]; then
            add_mount "/dev" "/dev"
        fi
        if [ -e "/tmp/.X11-unix" ]; then
            add_mount "/tmp/.X11-unix" "/tmp/.X11-unix"
        fi
        add_service_entry '    network_mode: host'
        ;;
esac

mkdir -p "$generated_dir"

{
    printf '%s\n' '# Generated by generate-local-override.sh - do not commit'
    printf '%s\n' 'services:'
    printf '%s\n' '  rmgo-develop:'
    if [ -n "$extra_service_entries" ]; then
        printf '%b' "$extra_service_entries"
    fi
    printf '%s\n' '    environment:'
    if [ -n "$environment_entries" ]; then
        printf '%b' "$environment_entries"
    else
        printf '%s\n' '      {}'
    fi
    printf '%s\n' '    volumes:'
    if [ -n "$mounts" ]; then
        printf '%b' "$mounts"
    else
        printf '%s\n' '      []'
    fi
} > "$output_file"
