services:
  rmgo-develop:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    privileged: true
    init: true
    command: /bin/bash -lc "while sleep 1000; do :; done"
    working_dir: /workspaces/rmgo
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    volumes:
      - type: bind
        source: ..
        target: /workspaces/rmgo
      - type: volume
        source: rmgo-ws-build
        target: /workspaces/rmgo/rmgo_ws/build
      - type: volume
        source: rmgo-ws-install
        target: /workspaces/rmgo/rmgo_ws/install
      - type: volume
        source: rmgo-ws-log
        target: /workspaces/rmgo/rmgo_ws/log

volumes:
  rmgo-ws-build:
  rmgo-ws-install:
  rmgo-ws-log:
