controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_controller:
      type: rmgo_core/OmniWheelController

    chassis_power_controller:
      type: rmgo_core/ChassisPowerController

    chassis_controller:
      type: rmgo_core/ChassisController

    teleop_remote_controller:
      type: rmgo_core/TeleopRemoteController

    gimbal_position_controller:
      type: position_controllers/JointGroupPositionController

chassis_controller:
  ros__parameters:
    target_controller_name: chassis_power_controller
    wheel_joints:
      - left_front_wheel_joint
      - left_back_wheel_joint
      - right_back_wheel_joint
      - right_front_wheel_joint
    wheel_state_interface_name: velocity
    wheel_radius: 0.07
    chassis_radius_x: 0.15897
    chassis_radius_y: 0.15897
    linear_x_kp: 0.0
    linear_x_ki: 0.0
    linear_x_kd: 0.0
    linear_y_kp: 0.0
    linear_y_ki: 0.0
    linear_y_kd: 0.0
    angular_z_kp: 0.0
    angular_z_ki: 0.0
    angular_z_kd: 0.0
    trace_commands: false

chassis_power_controller:
  ros__parameters:
    target_controller_name: omni_wheel_controller
    trace_commands: false

omni_wheel_controller:
  ros__parameters:
    wheel_joints:
      - left_front_wheel_joint
      - left_back_wheel_joint
      - right_back_wheel_joint
      - right_front_wheel_joint
    command_interface_name: velocity
    wheel_radius: 0.07
    chassis_radius_x: 0.15897
    chassis_radius_y: 0.15897
    max_wheel_velocity: 40.0
    trace_commands: false

teleop_remote_controller:
  ros__parameters:
    target_controller_name: chassis_controller
    cmd_vel_topic: /cmd_vel
    command_timeout: 2.0
    trace_commands: false

gimbal_position_controller:
  ros__parameters:
    joints:
      - yaw_joint
      - pitch_joint
