controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_controller:
      type: rmgo_core/OmniWheelController

    chassis_power_controller:
      type: rmgo_core/ChassisPowerController

    chassis_controller:
      type: rmgo_core/ChassisController

    teleop_remote_controller:
      type: rmgo_core/TeleopRemoteController

    simple_gimbal_controller:
      type: rmgo_core/SimpleGimbalController

chassis_controller:
  ros__parameters:
    target_controller_name: chassis_power_controller
    yaw_joint_name: yaw_joint
    yaw_state_interface_name: position
    command_source_frame: yaw
    twist_angular: 0.5235987755982988
    follow_velocity_feedforward: 0.0
    follow_kp: 7.0
    follow_ki: 0.0
    follow_kd: 0.0
    follow_output_min: -16.0
    follow_output_max: 16.0

chassis_power_controller:
  ros__parameters:
    target_controller_name: omni_wheel_controller
    safety_power: 80.0
    buffer_threshold: 30.0
    power_gain: 0.5
    max_power_limit: 95.0
    full_speed_power_limit: 95.0
    max_linear_x_velocity: 4.0
    max_linear_y_velocity: 4.0
    max_angular_z_velocity: 10.0

omni_wheel_controller:
  ros__parameters:
    wheel_joints:
      - left_front_wheel_joint
      - left_back_wheel_joint
      - right_back_wheel_joint
      - right_front_wheel_joint
    command_interface_name: velocity
    wheel_state_interface_name: velocity
    wheel_radius: 0.07
    chassis_radius_x: 0.15897
    chassis_radius_y: 0.15897
    max_wheel_velocity: 40.0
    linear_x_kp: 0.0
    linear_x_ki: 0.0
    linear_x_kd: 0.0
    linear_y_kp: 0.0
    linear_y_ki: 0.0
    linear_y_kd: 0.0
    angular_z_kp: 0.0
    angular_z_ki: 0.0
    angular_z_kd: 0.0

teleop_remote_controller:
  ros__parameters:
    target_controller_name: chassis_controller
    target_gimbal_controller_name: simple_gimbal_controller
    cmd_vel_topic: /cmd_vel
    cmd_gimbal_topic: /cmd_gimbal
    mode_topic: /cmd_chassis_mode
    command_timeout: 2.0

simple_gimbal_controller:
  ros__parameters:
    yaw_joint_name: yaw_joint
    pitch_joint_name: pitch_joint
    command_interface_name: position
    state_interface_name: position
    pitch_lower_limit: -0.5098
    pitch_upper_limit: 0.2262
